import {MigrationInterface, QueryRunner} from "typeorm";

export class init1663575040423 implements MigrationInterface {
    name = 'init1663575040423'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "admins_role_enum" AS ENUM('patient', 'doctor', 'admin', 'manager')`);
        await queryRunner.query(`CREATE TABLE "admins" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role" "admins_role_enum" NOT NULL DEFAULT 'admin', "email" text NOT NULL, "password" text NOT NULL, "firstName" text NOT NULL, "lastName" text NOT NULL, CONSTRAINT "admin_email" UNIQUE ("email"), CONSTRAINT "PK_e3b38270c97a854c48d2e80874e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hospitals" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "patientsLimit" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_02738c80d71453bc3e369a01766" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hospitals_doctors" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "doctorId" uuid NOT NULL, "hospitalId" uuid NOT NULL, CONSTRAINT "HOSPITALS_DOCTORS_UQ" UNIQUE ("doctorId", "hospitalId"), CONSTRAINT "PK_7048cf5918d0fba9412ca9f50c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "doctors_language_enum" AS ENUM('ru', 'en', 'kz', 'de')`);
        await queryRunner.query(`CREATE TYPE "doctors_role_enum" AS ENUM('patient', 'doctor', 'admin', 'manager')`);
        await queryRunner.query(`CREATE TABLE "doctors" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "language" "doctors_language_enum" NOT NULL DEFAULT 'ru', "email" text NOT NULL, "password" text NOT NULL, "notificationsSettings" jsonb NOT NULL DEFAULT '{"uploadAnalyzesByPatients":true,"criticalIndicators":true,"contactMeRequest":true}', "role" "doctors_role_enum" NOT NULL DEFAULT 'doctor', CONSTRAINT "DOCTOR_EMAIL_UQ" UNIQUE ("email"), CONSTRAINT "PK_8207e7889b50ee3695c2b8154ff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "doctor_notifications_kind_enum" AS ENUM('uploadAnalyzesByPatients', 'criticalIndicators', 'contactMeRequest')`);
        await queryRunner.query(`CREATE TABLE "doctor_notifications" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "doctorId" uuid NOT NULL, "patientId" uuid NOT NULL, "title" text NOT NULL, "description" text NOT NULL, "kind" "doctor_notifications_kind_enum" NOT NULL, "extraData" jsonb, "isRead" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_fd22ec57725544fb647c924ce36" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "doctors_patients" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "doctorId" uuid NOT NULL, "patientId" uuid NOT NULL, CONSTRAINT "DOCTORS_PATIENTS_UQ" UNIQUE ("patientId"), CONSTRAINT "PK_b2a8d1b1282945c1bd694e900c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "patient_analyzes" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patientId" uuid NOT NULL, "doctorId" uuid NOT NULL, "filename" text NOT NULL, "fileKey" text NOT NULL, "isViewed" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_203e14010fe5e801cc317e18c04" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "patients_role_enum" AS ENUM('patient', 'doctor', 'admin', 'manager')`);
        await queryRunner.query(`CREATE TYPE "patients_lastauthprovider_enum" AS ENUM('email')`);
        await queryRunner.query(`CREATE TYPE "patients_language_enum" AS ENUM('ru', 'en', 'kz', 'de')`);
        await queryRunner.query(`CREATE TABLE "patients" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role" "patients_role_enum" NOT NULL DEFAULT 'patient', "isFirstSignUp" boolean NOT NULL DEFAULT true, "email" text, "password" text, "fcmToken" text, "lastAuthProvider" "patients_lastauthprovider_enum" NOT NULL DEFAULT 'email', "notificationsSettings" jsonb NOT NULL DEFAULT '{"newSurvey":true}', "language" "patients_language_enum" NOT NULL DEFAULT 'ru', "inviteEndAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_a7f0b9fcbb3469d5ec0b0aceaa7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "patient_notifications_kind_enum" AS ENUM('newSurvey')`);
        await queryRunner.query(`CREATE TABLE "patient_notifications" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patientId" uuid NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL, "kind" "patient_notifications_kind_enum" NOT NULL, "extraData" jsonb NOT NULL, "doctorId" uuid NOT NULL, "isRead" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_82e018fea0196046f3a9ceda633" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hospitals_patients" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patientId" uuid NOT NULL, "hospitalId" uuid NOT NULL, "medicalCardNumber" text NOT NULL, "firstName" character varying, "lastName" character varying, CONSTRAINT "HOSPITALS_PATIENTS_UQ" UNIQUE ("hospitalId", "patientId"), CONSTRAINT "PK_f025bae4fd184297ac85ecad434" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "doctor_invitations" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" text NOT NULL, "hospitalId" uuid, CONSTRAINT "DOCTOR_INVITATIONS_EMAIL_UQ" UNIQUE ("email"), CONSTRAINT "PK_9c38e88bfa431e81935fbb2ecbc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "question_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" text NOT NULL, CONSTRAINT "PK_c4f3431b15f8c8c2e9bf8e489e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_332758a5931e0ac1b0ccdd866c" ON "question_categories" ("name") `);
        await queryRunner.query(`CREATE TABLE "question_categories_questions" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "questionId" uuid NOT NULL, "questionCategoryId" uuid NOT NULL, CONSTRAINT "PK_20e149836ed156edc0e24d2ced7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "question_options" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "text" text NOT NULL, "index" integer NOT NULL, "questionId" uuid NOT NULL, CONSTRAINT "PK_13be20e51c0738def32f00cf7d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "questions_type_enum" AS ENUM('radio', 'checkbox', 'numeric', 'scale', 'pressure', 'temperature', 'weight', 'pulse')`);
        await queryRunner.query(`CREATE TABLE "questions" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "doctorId" uuid, "type" "questions_type_enum" NOT NULL, "indicators" jsonb, "title" text NOT NULL, "isCustom" boolean NOT NULL DEFAULT false, "questionCategoryQuestionsId" uuid, CONSTRAINT "PK_08a6d4b0f49ff300bf3a0ca60ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drugs_questions" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "drugId" uuid NOT NULL, "questionId" uuid NOT NULL, CONSTRAINT "PK_7cc19ac0c2465bbcd6ec35e6d02" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "drugs" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, CONSTRAINT "PK_a3788abdeb2ec977862b17351ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_68ee1c951216ab60f778d0dbed" ON "drugs" ("name") `);
        await queryRunner.query(`CREATE TYPE "hospital_managers_role_enum" AS ENUM('patient', 'doctor', 'admin', 'manager')`);
        await queryRunner.query(`CREATE TABLE "hospital_managers" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" text NOT NULL, "password" text NOT NULL, "hospitalId" uuid NOT NULL, "role" "hospital_managers_role_enum" NOT NULL DEFAULT 'manager', CONSTRAINT "HOSPITAL_MANAGERS_EMAIL_UQ" UNIQUE ("email"), CONSTRAINT "PK_a7218502e7f204d834f70699957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "survey_templates_period_enum" AS ENUM('everyday', 'everyTwoDays', 'onceAWeek', 'onceInTwoWeeks')`);
        await queryRunner.query(`CREATE TYPE "survey_templates_kind_enum" AS ENUM('private', 'public')`);
        await queryRunner.query(`CREATE TYPE "survey_templates_status_enum" AS ENUM('active', 'canceled')`);
        await queryRunner.query(`CREATE TABLE "survey_templates" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "doctorId" uuid NOT NULL, "patientId" uuid NOT NULL, "title" text NOT NULL, "startAt" TIMESTAMP NOT NULL, "endAt" TIMESTAMP NOT NULL, "period" "survey_templates_period_enum" NOT NULL, "kind" "survey_templates_kind_enum" NOT NULL, "status" "survey_templates_status_enum", "lastSentAt" TIMESTAMP, "timezoneOffset" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_938015fccae381778b558d2af89" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "survey_templates_questions" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "criticalIndicators" jsonb, "templateId" uuid NOT NULL, "questionId" uuid NOT NULL, "criticalAnswerId" uuid, "criticalAnswersIds" uuid array, CONSTRAINT "SURVEY_TEMPLATES_QUESTIONS_UQ" UNIQUE ("templateId", "questionId"), CONSTRAINT "PK_a92324658728b454ca75bcb356e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "survey_templates_drugs" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "drugId" uuid NOT NULL, "templateId" uuid NOT NULL, CONSTRAINT "PK_430f1bcadfda9e8439b1abd544f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "surveys_status_enum" AS ENUM('active', 'canceled', 'completed')`);
        await queryRunner.query(`CREATE TABLE "surveys" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "surveys_status_enum" NOT NULL, "templateId" uuid NOT NULL, "patientId" uuid NOT NULL, "doctorId" uuid NOT NULL, CONSTRAINT "PK_1b5e3d4aaeb2321ffa98498c971" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "survey_answers" ("createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "isCritical" boolean NOT NULL DEFAULT false, "answerValue" jsonb, "answerQuestionOptionId" uuid, "answerQuestionOptionsIds" uuid array, "questionId" uuid NOT NULL, "surveyId" uuid NOT NULL, CONSTRAINT "PK_e4cab112318f766c93435f77a1a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" ADD CONSTRAINT "FK_13693845a646bf8c7844eb6ddfb" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" ADD CONSTRAINT "FK_a195e01627b8723c739799b1bf0" FOREIGN KEY ("hospitalId") REFERENCES "hospitals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor_notifications" ADD CONSTRAINT "FK_bcc4061384e704314c79936e280" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor_notifications" ADD CONSTRAINT "FK_51e197c9550f18d3b3856037914" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" ADD CONSTRAINT "FK_a17affe0ac9517e25fd2c6ac963" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" ADD CONSTRAINT "FK_ac4033f578326226212d4ef8f17" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_analyzes" ADD CONSTRAINT "FK_d6fcad75d184477cfac6a719a4b" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_notifications" ADD CONSTRAINT "FK_6cf57a11192b0a69177c69d566e" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_notifications" ADD CONSTRAINT "FK_77d49be1eaa2aed0136cd61fa66" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ADD CONSTRAINT "FK_c4635a397cb663e6bf30c604c5a" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" ADD CONSTRAINT "FK_743353079291feb50cc978759c6" FOREIGN KEY ("hospitalId") REFERENCES "hospitals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor_invitations" ADD CONSTRAINT "FK_63dc09e4f52f94c5bb3c045a491" FOREIGN KEY ("hospitalId") REFERENCES "hospitals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_categories_questions" ADD CONSTRAINT "FK_8bf8c8819f88049de96d3676d00" FOREIGN KEY ("questionId") REFERENCES "questions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_categories_questions" ADD CONSTRAINT "FK_1fb1ecdaa9b63568cc74b367b7c" FOREIGN KEY ("questionCategoryId") REFERENCES "question_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "question_options" ADD CONSTRAINT "FK_c654af7759a681f1b1addbe35bf" FOREIGN KEY ("questionId") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_89f38969625e9a4ab40aad904ca" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_6cb0576759c50d899bc3d077a6f" FOREIGN KEY ("questionCategoryQuestionsId") REFERENCES "question_categories_questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drugs_questions" ADD CONSTRAINT "FK_a011a3d387e6bbdb0fb3e8764b9" FOREIGN KEY ("drugId") REFERENCES "drugs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drugs_questions" ADD CONSTRAINT "FK_d1ed6426c9c484c3058f4d575f1" FOREIGN KEY ("questionId") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hospital_managers" ADD CONSTRAINT "FK_2e7ef50decd89c4126e36db78ba" FOREIGN KEY ("hospitalId") REFERENCES "hospitals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "survey_templates" ADD CONSTRAINT "FK_e53a3544e6953d473d065dbf1c7" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "survey_templates" ADD CONSTRAINT "FK_970afecda281df20bbade459b1f" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "survey_templates_questions" ADD CONSTRAINT "FK_cf8915738792747c77ea78c0b95" FOREIGN KEY ("templateId") REFERENCES "survey_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "survey_templates_questions" ADD CONSTRAINT "FK_177b71ed7ae84b8132137625025" FOREIGN KEY ("questionId") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "survey_templates_questions" ADD CONSTRAINT "FK_50fc5fd83f5fbf42c24d074f083" FOREIGN KEY ("criticalAnswerId") REFERENCES "question_options"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "survey_templates_drugs" ADD CONSTRAINT "FK_374626ea7311d1e856b56a76fb4" FOREIGN KEY ("drugId") REFERENCES "drugs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "survey_templates_drugs" ADD CONSTRAINT "FK_00d41ea28d0f3909b15fd285af7" FOREIGN KEY ("templateId") REFERENCES "survey_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surveys" ADD CONSTRAINT "FK_436db4881a9448358524ab376d9" FOREIGN KEY ("templateId") REFERENCES "survey_templates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surveys" ADD CONSTRAINT "FK_777cd9a37556696f4e2218179cb" FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surveys" ADD CONSTRAINT "FK_51cb3ddf845ae8a64a8131a662c" FOREIGN KEY ("doctorId") REFERENCES "doctors"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "survey_answers" ADD CONSTRAINT "FK_350641f47cde3fa7c44545fe9ac" FOREIGN KEY ("answerQuestionOptionId") REFERENCES "question_options"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "survey_answers" ADD CONSTRAINT "FK_92fd3faf28a0dd93140689166e5" FOREIGN KEY ("questionId") REFERENCES "questions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "survey_answers" ADD CONSTRAINT "FK_59819876d0cf9177a7edbe1a15d" FOREIGN KEY ("surveyId") REFERENCES "surveys"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "survey_answers" DROP CONSTRAINT "FK_59819876d0cf9177a7edbe1a15d"`);
        await queryRunner.query(`ALTER TABLE "survey_answers" DROP CONSTRAINT "FK_92fd3faf28a0dd93140689166e5"`);
        await queryRunner.query(`ALTER TABLE "survey_answers" DROP CONSTRAINT "FK_350641f47cde3fa7c44545fe9ac"`);
        await queryRunner.query(`ALTER TABLE "surveys" DROP CONSTRAINT "FK_51cb3ddf845ae8a64a8131a662c"`);
        await queryRunner.query(`ALTER TABLE "surveys" DROP CONSTRAINT "FK_777cd9a37556696f4e2218179cb"`);
        await queryRunner.query(`ALTER TABLE "surveys" DROP CONSTRAINT "FK_436db4881a9448358524ab376d9"`);
        await queryRunner.query(`ALTER TABLE "survey_templates_drugs" DROP CONSTRAINT "FK_00d41ea28d0f3909b15fd285af7"`);
        await queryRunner.query(`ALTER TABLE "survey_templates_drugs" DROP CONSTRAINT "FK_374626ea7311d1e856b56a76fb4"`);
        await queryRunner.query(`ALTER TABLE "survey_templates_questions" DROP CONSTRAINT "FK_50fc5fd83f5fbf42c24d074f083"`);
        await queryRunner.query(`ALTER TABLE "survey_templates_questions" DROP CONSTRAINT "FK_177b71ed7ae84b8132137625025"`);
        await queryRunner.query(`ALTER TABLE "survey_templates_questions" DROP CONSTRAINT "FK_cf8915738792747c77ea78c0b95"`);
        await queryRunner.query(`ALTER TABLE "survey_templates" DROP CONSTRAINT "FK_970afecda281df20bbade459b1f"`);
        await queryRunner.query(`ALTER TABLE "survey_templates" DROP CONSTRAINT "FK_e53a3544e6953d473d065dbf1c7"`);
        await queryRunner.query(`ALTER TABLE "hospital_managers" DROP CONSTRAINT "FK_2e7ef50decd89c4126e36db78ba"`);
        await queryRunner.query(`ALTER TABLE "drugs_questions" DROP CONSTRAINT "FK_d1ed6426c9c484c3058f4d575f1"`);
        await queryRunner.query(`ALTER TABLE "drugs_questions" DROP CONSTRAINT "FK_a011a3d387e6bbdb0fb3e8764b9"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "FK_6cb0576759c50d899bc3d077a6f"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "FK_89f38969625e9a4ab40aad904ca"`);
        await queryRunner.query(`ALTER TABLE "question_options" DROP CONSTRAINT "FK_c654af7759a681f1b1addbe35bf"`);
        await queryRunner.query(`ALTER TABLE "question_categories_questions" DROP CONSTRAINT "FK_1fb1ecdaa9b63568cc74b367b7c"`);
        await queryRunner.query(`ALTER TABLE "question_categories_questions" DROP CONSTRAINT "FK_8bf8c8819f88049de96d3676d00"`);
        await queryRunner.query(`ALTER TABLE "doctor_invitations" DROP CONSTRAINT "FK_63dc09e4f52f94c5bb3c045a491"`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" DROP CONSTRAINT "FK_743353079291feb50cc978759c6"`);
        await queryRunner.query(`ALTER TABLE "hospitals_patients" DROP CONSTRAINT "FK_c4635a397cb663e6bf30c604c5a"`);
        await queryRunner.query(`ALTER TABLE "patient_notifications" DROP CONSTRAINT "FK_77d49be1eaa2aed0136cd61fa66"`);
        await queryRunner.query(`ALTER TABLE "patient_notifications" DROP CONSTRAINT "FK_6cf57a11192b0a69177c69d566e"`);
        await queryRunner.query(`ALTER TABLE "patient_analyzes" DROP CONSTRAINT "FK_d6fcad75d184477cfac6a719a4b"`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" DROP CONSTRAINT "FK_ac4033f578326226212d4ef8f17"`);
        await queryRunner.query(`ALTER TABLE "doctors_patients" DROP CONSTRAINT "FK_a17affe0ac9517e25fd2c6ac963"`);
        await queryRunner.query(`ALTER TABLE "doctor_notifications" DROP CONSTRAINT "FK_51e197c9550f18d3b3856037914"`);
        await queryRunner.query(`ALTER TABLE "doctor_notifications" DROP CONSTRAINT "FK_bcc4061384e704314c79936e280"`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" DROP CONSTRAINT "FK_a195e01627b8723c739799b1bf0"`);
        await queryRunner.query(`ALTER TABLE "hospitals_doctors" DROP CONSTRAINT "FK_13693845a646bf8c7844eb6ddfb"`);
        await queryRunner.query(`DROP TABLE "survey_answers"`);
        await queryRunner.query(`DROP TABLE "surveys"`);
        await queryRunner.query(`DROP TYPE "surveys_status_enum"`);
        await queryRunner.query(`DROP TABLE "survey_templates_drugs"`);
        await queryRunner.query(`DROP TABLE "survey_templates_questions"`);
        await queryRunner.query(`DROP TABLE "survey_templates"`);
        await queryRunner.query(`DROP TYPE "survey_templates_status_enum"`);
        await queryRunner.query(`DROP TYPE "survey_templates_kind_enum"`);
        await queryRunner.query(`DROP TYPE "survey_templates_period_enum"`);
        await queryRunner.query(`DROP TABLE "hospital_managers"`);
        await queryRunner.query(`DROP TYPE "hospital_managers_role_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_68ee1c951216ab60f778d0dbed"`);
        await queryRunner.query(`DROP TABLE "drugs"`);
        await queryRunner.query(`DROP TABLE "drugs_questions"`);
        await queryRunner.query(`DROP TABLE "questions"`);
        await queryRunner.query(`DROP TYPE "questions_type_enum"`);
        await queryRunner.query(`DROP TABLE "question_options"`);
        await queryRunner.query(`DROP TABLE "question_categories_questions"`);
        await queryRunner.query(`DROP INDEX "IDX_332758a5931e0ac1b0ccdd866c"`);
        await queryRunner.query(`DROP TABLE "question_categories"`);
        await queryRunner.query(`DROP TABLE "doctor_invitations"`);
        await queryRunner.query(`DROP TABLE "hospitals_patients"`);
        await queryRunner.query(`DROP TABLE "patient_notifications"`);
        await queryRunner.query(`DROP TYPE "patient_notifications_kind_enum"`);
        await queryRunner.query(`DROP TABLE "patients"`);
        await queryRunner.query(`DROP TYPE "patients_language_enum"`);
        await queryRunner.query(`DROP TYPE "patients_lastauthprovider_enum"`);
        await queryRunner.query(`DROP TYPE "patients_role_enum"`);
        await queryRunner.query(`DROP TABLE "patient_analyzes"`);
        await queryRunner.query(`DROP TABLE "doctors_patients"`);
        await queryRunner.query(`DROP TABLE "doctor_notifications"`);
        await queryRunner.query(`DROP TYPE "doctor_notifications_kind_enum"`);
        await queryRunner.query(`DROP TABLE "doctors"`);
        await queryRunner.query(`DROP TYPE "doctors_role_enum"`);
        await queryRunner.query(`DROP TYPE "doctors_language_enum"`);
        await queryRunner.query(`DROP TABLE "hospitals_doctors"`);
        await queryRunner.query(`DROP TABLE "hospitals"`);
        await queryRunner.query(`DROP TABLE "admins"`);
        await queryRunner.query(`DROP TYPE "admins_role_enum"`);
    }

}
